#ifndef __XARM_MSGS_H
#define __XARM_MSGS_H

#include <xarm_msgs/SetInt16.h>
#include <xarm_msgs/SetFloat32.h>
#include <xarm_msgs/TCPOffset.h>
#include <xarm_msgs/SetLoad.h>
#include <xarm_msgs/SetAxis.h>
#include <xarm_msgs/Move.h>
#include <xarm_msgs/RobotMsg.h>
#include <xarm_msgs/IOState.h>
#include <xarm_msgs/CIOState.h>
#include <xarm_msgs/VeloMoveMsg.h>
#include <xarm_msgs/SetDigitalIO.h>
#include <xarm_msgs/GetDigitalIO.h>
#include <xarm_msgs/GetControllerDigitalIO.h>
#include <xarm_msgs/SetControllerAnalogIO.h>
#include <xarm_msgs/GetAnalogIO.h>
#include <xarm_msgs/ClearErr.h>
#include <xarm_msgs/GetErr.h>
#include <xarm_msgs/GripperConfig.h>
#include <xarm_msgs/GripperMove.h>
#include <xarm_msgs/GripperState.h>
#include <xarm_msgs/SetToolModbus.h>
#include <xarm_msgs/ConfigToolModbus.h>
#include <xarm_msgs/MoveAxisAngle.h>
#include <xarm_msgs/MoveVelo.h>
#include <xarm_msgs/MoveVelocity.h>
#include <xarm_msgs/SetMultipleInts.h>
#include <xarm_msgs/PlayTraj.h>
#include <xarm_msgs/SetString.h>
#include <xarm_msgs/GetFloat32List.h>
#include <xarm_msgs/GetInt32.h>
#include <xarm_msgs/SetModbusTimeout.h>
#include <xarm_msgs/GetSetModbusData.h>
#include <xarm_msgs/Call.h>
#include <xarm_msgs/FtCaliLoad.h>
#include <xarm_msgs/FtIdenLoad.h>
#include <xarm_msgs/VacuumGripperCtrl.h>

#endif // __XARM_MSGS_H