# request: command specification for velocity executions.
# Units:
#	joint space/angles: radian/s
#	Cartesian space: mm/s, radian/s.

# velocities: the velocity list of the joints/tcp
#   For vc_set_jointv service: [joint1_velocity, ..., joint7_velocity]
#   For vc_set_linev service: [x_velocity, y_svelocity, z_velocity, roll_velocity, pitch_velocity, yaw_velocity]
float32[] velocities

# jnt_sync: this is special for vc_set_jointv service, meaning whether all joints accelerate and decelerate synchronously
int16 jnt_sync

# coord: this is special for vc_set_linev service, meaning whether is tool coordinate or not
int16 coord

---

# response: 
#	ret is 0 for successful execution and others for errors or warnings occured
#	message is a string returned by function, indicating execution status.

int16 ret

string message