# request: command specification for motion executions.
# Units:
#	joint space/angles: radian.
#	Cartesian space: mm, mm/s, and mm/s^2.
#	time: sec

# pose: target coordinate. 
#	For Joint Space target，pose dimention is the number of joints. element as each target joint position.
#	For Cartesian target: pose dimention is 6 for (x, y, z, roll, pitch, yaw)

float32[] pose

# mvvelo: (value range: 0 ~ 1000) specified maximum velocity during execution. linear (0 to 1000 mm/s)  or angular (range 0~1000 for 0 to 3.14 rad/s) velocity.

float32 mvvelo

# mvacc: specified maximum linear acceleration (mm/s^2) during execution. (angular acceleration is fixed currently).

float32 mvacc

# mvtime: currently do not have any special meaning, please just give it 0. 
# PLEASE NOTE: after firmware version 1.5, For servo_cartesian motion, mvtime will be used as indicator of coordinate system. (0 for BASE coordinate, non-zero for TOOL coordinate)  

float32 mvtime

# mvradii: this is special for move_ineb service, meaning the blending radius between 2 straight path trajectories, 0 for no blend.

float32 mvradii

---

# response: 
#	ret is 0 for successful execution and others for errors or warnings occured
#	message is a string returned by function, indicating execution status.

int16 ret

string message