# unsigned char data to be sent to tool device through modbus
uint8[] send_data

# Specify the anticipated maximum respond data length in bytes
int16 respond_len

---

int16 ret
string message
uint8[] respond_data